//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace livegui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool closeLauncher {
            get {
                return ((bool)(this["closeLauncher"]));
            }
            set {
                this["closeLauncher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("livestreamer")]
        public string livestreamerLocation {
            get {
                return ((string)(this["livestreamerLocation"]));
            }
            set {
                this["livestreamerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string urls {
            get {
                return ((string)(this["urls"]));
            }
            set {
                this["urls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alarmFocus {
            get {
                return ((bool)(this["alarmFocus"]));
            }
            set {
                this["alarmFocus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"afreecatv.com|afreeca.tv|aftonbladet.se|aliez.tv|live.daserste.de|ardmediathek.de|arte.tv|azubu.tv|be-at.tv|bambuser.com|chaturbate.com|connectcast.tv|crunchyroll.com|cybergame.tv|dailymotion.com|video.disney.de|disneychannel.de|dommune.com|douyutv.com|api.dmcloud.net|dr.dk|euronews.com|filmon.com|filmon.us|furstre.am|gaminglive.tv|gomexp.com|goodgame.ru|hitbox.tv|itv.com/itvplayer|leton.tv|livestation.com|new.livestream.com|media.ccc.de|streaming.media.ccc.de|mips.tv|mlg.tv|nhk.or.jp/nhkworld|nos.nl|npo.nl|tv.nrk.no|radio.nrk.no|original.livestream.com|periscope.tv|picarto.tv|rtve.es|kanal5play.se|kanal9play.se|kanal11play.se|seemeplay.ru|speedrunslive.com|ssh101.com|streamingvideoprovider.co.uk|streamlive.to|svtplay.se|svtflow.se|oppetarkiv.se|star.plu.cn|star.tga.plu.cn|tv3.cat|tv4play.se|fotbollskanalen.se|tvcatchup.com|tvplayer.com|twitch.tv|ustream.tv|vaughnlive.tv|breakers.tv|instagib.tv|vapers.tv|veetle.com|vgtv.no|viagame.com|tv3play.se|tv3play.no|tv3play.dk|tv3play.ee|tv3play.lt|tv3play.lv|tv6play.se|tv6play.no|tv8play.se|tv10play.se|viasat4play.no|play.tv3.lt|juicyplay.se|wat.tv|weeb.tv|youtube.com|youtu.be|zdf.de")]
        public string plugins {
            get {
                return ((string)(this["plugins"]));
            }
            set {
                this["plugins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mediaPlayerLocation {
            get {
                return ((string)(this["mediaPlayerLocation"]));
            }
            set {
                this["mediaPlayerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useCustomMediaPlayer {
            get {
                return ((bool)(this["useCustomMediaPlayer"]));
            }
            set {
                this["useCustomMediaPlayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string launchParameters {
            get {
                return ((string)(this["launchParameters"]));
            }
            set {
                this["launchParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Best|Worst")]
        public string qualities {
            get {
                return ((string)(this["qualities"]));
            }
            set {
                this["qualities"] = value;
            }
        }
    }
}
